logging:
  level:
    root: warn
    org.springframework: info
    com.intelligentblokus: info
    com:
      intelligentblokus:
        intelligentblokus:
          BlokusService: info
          play_strategy:
            impl:
              BlokusMinimaxPlayStrategy: info

blokus:
  players:
    white: minimax
    black: big_pieces
