logging:
  level:
    root: warn
    org.springframework: info
    com.intelligentblokus: info
    com.intelligentblokus.intelligentblokus.BlokusService: debug

blokus:
  players:
    white: random
    black: big_pieces
